### ISSUE TITLE
Polygon outline

### ISSUE THREAD

**Issue by jonasrotilli** [Orbitist/kriging#1]
Very good this book!
Does anyone know how I could add a contour between the polygon? I have a map of a farm that have several polignos (which are the divisions of the farm and smaller parcels), I need it to have a contour in each polygon.

**Comment by ngunner** [comment]
I'm not sure on this. This repo was based on https://github.com/oeo4b/kriging.js. You'll probably have more luck looking for an answer to your issue over there. Cheers!
